<?php echo $this->getContent(); ?>

<div class="row">
<div class="col-xs-12 col-md-4 col-sm-2 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-4 col-sm-8">
	<?php $this->flashSession->output();?>
	
	<form class="form-horizontal" action="<?php echo $this->url->get("auth/authenticate") ?>" method="POST">
	  <div class="form-group">
	    <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
	    <div class="col-sm-10">
	      <input name="name" type="text" class="form-control" id="inputEmail3" placeholder="User Name">
	    </div>
	  </div>
	  <div class="form-group">
	    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
	    <div class="col-sm-10">
	      <input name="pass" type="password" class="form-control" id="inputPassword3" placeholder="Password">
	    </div>
	  </div>

	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	      <button type="submit" class="btn btn-default">Sign in</button>
	    </div>
	  </div>
	</form>
	
</div>

<div class="col-xs-12 col-md-4 col-sm-2 visible-lg-* visible-md-*"></div>
</div>
