<?php echo $this->getContent(); ?>

<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<?php $this->flashSession->output();?>
<!--start content-->
<h2><?php echo $question->question;?></h2>

<form class="form-horizontal" action="<?php echo $this->url->get( $this->router->getControllerName() . "/save-belong-to-level"); ?>" method="POST">
<input type="hidden" name="question_id" value="<?php echo $question->id;?>" >

  <div class="form-group">

  	<?php foreach($levels as $item):?>
    <div class="col-sm-3">
      <div class="checkbox">
        <label>
          <input name="levels[]" type="checkbox" value="<?php echo $item->id;?>" <?php echo ( $levelQuestion[$item->id] ) ? "checked" : "";?> > <?php echo $item->name;?>
        </label>
      </div>
    </div>
	<?php endforeach;?>

  </div>

  <div class="form-group">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </div>
</form>



<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

<script>

$(document).ready(function() {



});

</script>