<?php echo $this->getContent(); ?>
<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<h1>New Level</h1>
	<?php $this->flashSession->output();?>
	
<!--start content-->


<form class="form-horizontal" action="<?php echo $this->url->get( $this->router->getControllerName() . "/save-category");?>" method="POST">
  <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input name="name" type="text" class="form-control" id="inputName" placeholder="Name">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>


<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

