<?php echo $this->getContent(); ?>
<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<h1>New Level</h1>
	<?php $this->flashSession->output();?>
	
<!--start content-->


<form class="form-horizontal" action="<?php echo $this->url->get( $this->router->getControllerName() . "/save-level");?>" method="POST">
  <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input name="name" type="text" class="form-control" id="inputName" placeholder="Name">
    </div>
  </div>

  <div class="form-group">
    <label for="inputValue" class="col-sm-2 control-label">Value</label>
    <div class="col-sm-10">
      <input name="value" type="text" class="form-control" id="inputValue" placeholder="Value">
    </div>
  </div>

  <div class="form-group">
    <label for="inputCategory" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
		<select class="form-control" name="category_id" id="inputCategory">
			<?php foreach($select as $item):?>
				<option value="<?php echo $item->id?>"><?php echo $item->name?></option>
			<?php endforeach;?>
		</select>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>


<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

