<?php echo $this->getContent(); ?>

<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<h1>Categories
	<a href="<?php echo $this->url->get( $this->router->getControllerName() . "/add-category") ?>" class="btn btn-success fancybox fancybox.iframe"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
	</h1>
	<?php $this->flashSession->output();?>
	
<!--start content-->


<table align="center" class="table table-striped table-bordered table-hover dataTable" id="list">
    <thead>
        <tr>
            <th>Name</th>
            <th width="20px"></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($list as $item) { ?>
        <tr id="<?php echo $item->id ?>">
            <td><?php echo $item->name ?></td>
            <td class="vertical-middle text-center"><a href="<?php echo $this->url->get( $this->router->getControllerName() . "/delete-category/" . $item->id); ?>" class="red-color delete"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
        </tr>
    <?php } ?>
    </tbody>

</table>


<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

<script>

$(document).ready(function() {

    var table = $('#list').dataTable({
    	
    	"order": [[ 0, "asc" ]],
		aoColumns: [ {"sName": "name"}, { "bSortable": false }]

    }).makeEditable({
    	sUpdateURL: "<?php echo $this->url->get( $this->router->getControllerName() . "/ajax-editable-category") ?>",
        "aoColumns": [
                        {
                            onblur: 'submit',
                            indicator: 'Saving name ...'
                        },
                        {
                            onblur: 'submit',
                            indicator: 'Saving value ...'
                        },
                        null
                    ]

    });

});

</script>