<?php echo $this->getContent(); ?>

<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<h1>Levels
	<a href="<?php echo $this->url->get( $this->router->getControllerName() . "/add-level") ?>" class="btn btn-success fancybox fancybox.iframe"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
	</h1>
	<?php $this->flashSession->output();?>
	
<!--start content-->


<table align="center" class="table table-striped table-bordered table-hover dataTable" id="list">
    <thead>
        <tr>
            <th>Name</th>
            <th>Value</th>
            <th>Category</th>
            <th width="20px"></th>
            <th width="20px"></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($list as $item) { ?>
        <tr id="<?php echo $item->id ?>">
            <td><?php echo $item->name;?></td>
            <td><?php echo $item->value;?></td>
            <td><?php echo $item->Category->name;?></td>
            <td class="vertical-middle text-center"><a href="<?php echo $this->url->get( $this->router->getControllerName() . "/list-level-question/" . $item->id); ?>" class="fancybox fancybox.iframe" data-toggle="popover" title="List Question"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span></a></td>
            <td class="vertical-middle text-center"><a href="<?php echo $this->url->get( $this->router->getControllerName() . "/delete-level/" . $item->id); ?>" class="red-color delete"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
        </tr>
    <?php } ?>
    </tbody>

</table>


<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

<script>

$(document).ready(function() {

    var table = $('#list').dataTable({
    	
    	"order": [[ 2, "asc" ]],
		aoColumns: [ {"sName": "name"}, {"sName": "value"}, {"sName": "category_id"}, { "bSortable": false }, { "bSortable": false }]

    }).makeEditable({
    	sUpdateURL: "<?php echo $this->url->get( $this->router->getControllerName() . "/ajax-editable-level") ?>",
        "aoColumns": [
                        {
                            onblur: 'submit',
                            indicator: 'Saving name ...'
                        },
                        {
                            onblur: 'submit',
                            indicator: 'Saving value ...'
                        },
                        {
                        onblur: 'cancel',
                        type: 'select',
                        submit   : 'OK',
                        data: "<?php echo $select_string_value;?>",
                        indicator: 'Saving Category ...'
                    	},
                        null,
                        null
                    ]

    });

});

</script>