<?php echo $this->getContent(); ?>

<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<h1>Video</h1>
	<?php $this->flashSession->output();?>
<!--start content-->
<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="<?php echo $question->video;?>"></iframe>
</div>

<br>

<div class="col-xs-12 col-md-2 col-sm-12">
	<form class="form-horizontal" action="<?php echo $this->url->get( $this->router->getControllerName() . "/view-video-question");?>" method="POST">
		<input type="hidden" name="id" value="<?php echo $question->id;?>" >
	  <div class="form-group">
	    <label for="inputVideo" class="col-sm-2 control-label">Video URL</label>
	    <div class="col-sm-10">
	      <input name="video" type="text" class="form-control" id="inputVideo" placeholder="http://www.youtube.com/embed/owx3ao42kwI?rel=0">
	    </div>
	  </div>

	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	      <button type="submit" class="btn btn-success">Submit</button>
	    </div>
	  </div>
	</form>
</div>

<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

<script>

$(document).ready(function() {



});

</script>