<?php echo $this->getContent(); ?>

<div class="row">
<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>

<div class="col-xs-12 col-md-8 col-sm-12">
	<h1>Image</h1>
	<?php $this->flashSession->output();?>
	
<!--start content-->
<div class="wrapper col-md-3">
    <img class="img-responsive" src="<?php echo $question->img;?>"/>
</div>

<div class="row">
	<form class="form-horizontal" action="<?php echo $this->url->get( $this->router->getControllerName() . "/view-img-question");?>" method="POST">
		<input type="hidden" name="id" value="<?php echo $question->id;?>" >
	  <div class="form-group">
	    <label for="inputImg" class="col-sm-2 control-label">Image URL</label>
	    <div class="col-sm-10">
	      <input name="img" type="text" class="form-control" id="inputImg" placeholder="http://www.example.com/img.jpg">
	    </div>
	  </div>

	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	      <button type="submit" class="btn btn-success">Submit</button>
	    </div>
	  </div>
	</form>
</div>

<!--end content-->

</div>

<div class="col-xs-12 col-md-2 col-sm-12 visible-lg-* visible-md-*"></div>
</div>

<script>

$(document).ready(function() {



});

</script>