    <footer class="footer">
      <div align="center">
            <p class="text-muted"><?php echo date("Y");?> &copy; 24Hit.net.</p>
      </div>
    </footer>

<script type="text/javascript">

$(document).ready(function() {

	<?php /*
	$("ul#searchType>li").click(function(e){
		e.preventDefault();
		$("ul#searchType li").removeClass("selected");
		$(this).addClass("selected");
		$("#searchType").siblings("button").html( $(this).text() + " <span class=\"caret\"></span>" );
	});*/ ?>

	<?php /*
	$("ul.bible-version li").click(function(e){
		//e.preventDefault();
		//$("ul.bible-version li").removeClass("selected");
		//$(this).addClass("selected");
		//$(".bible-version").siblings("a").html( $(this).text() + " <span class=\"caret\"></span>" );
	});*/ ?>


	<?php /*
	$("li.bible-book").click(function(e){
		e.preventDefault();
		$("li.bible-book").removeClass("selected");
		$(this).addClass("selected");
		$(".bible-book-container").siblings("a").html( $(this).text() + " <span class=\"caret\"></span>" );

	});*/ ?>
	
	<?php /*
	$("a.chapter").click(function(e){
		e.preventDefault();
		$("a.chapter").removeClass("selected");
		$(this).addClass("selected");
		$(".bible-chapter-container").siblings("a").html( $(this).text() + " <span class=\"caret\"></span>" );
	});*/ ?>

});

</script>