<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url->get("admin");?>">Bible Trivia</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
    <ul class="nav navbar-nav">
      <li class="<?php echo ($this->router->getActionName() == "listQuestion") ? "active" : "";?>"><a href="<?php echo $this->url->get("admin/list-question");?>">Question</a></li>
      <li class="<?php echo ($this->router->getActionName() == "listLevel") ? "active" : "";?>"><a href="<?php echo $this->url->get("admin/list-level");?>">Level</a></li>
      <li class="<?php echo ($this->router->getActionName() == "listCategory") ? "active" : "";?>"><a href="<?php echo $this->url->get("admin/list-category");?>">Category</a></li>
    </ul>

      <?php if( !empty($logedin['name']) ):?>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?php echo $logedin['name'];?> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="<?php echo $this->url->get("auth/logout");?>">Logout</a></li>
          </ul>
        </li>

      </ul>
      <?php endif;?>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>