<?php echo $this->getContent(); ?>

<?php $this->flashSession->output();?>

<h4><?php echo $quiz['title'];?></h4>


<ul class="list-group question-list">

	<li class="list-group-item" id="quiz-">
		<a href="" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
		<input class="form-control" name="" value="">
		<ul  class="list-group" id="question-">
			<li class="list-group-item">
				<a href="" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
				<input class="form-control" name="" value="">
			</li>

		</ul>
	</li>
</ul>