<?php echo $this->getContent(); ?>

<?php $this->flashSession->output();?>

<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist" id="user-panel">
    <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><h4>Profile</h4></a></li>
    <li role="presentation"><a href="#quiz" aria-controls="quiz" role="tab" data-toggle="tab"><h4>Create Quiz</h4></a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    
    <div role="tabpanel" class="tab-pane active" id="profile">
		<h5>Update your password</h5>
		<form class="form-horizontal" action="<?php echo $this->url->get("user/update");?>" method="POST">
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-3 control-label">Email</label>
		    <div class="col-sm-9">
		      <input type="email" class="form-control" id="inputEmail3" name="email" value="<?php echo $rememberMe;?>" disabled>
		    </div>
		  </div>

		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-3 control-label">Old Password</label>
		    <div class="col-sm-9">
		      <input type="password" class="form-control" id="inputPassword3" placeholder="Password" name="password" required autofocus>
		    </div>
		  </div>

		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-3 control-label">New password</label>
		    <div class="col-sm-9">
		      <input type="password" class="form-control" id="inputPassword3" placeholder="New password" name="password_new" required>
		    </div>
		  </div>

		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-3 control-label">Confirm password</label>
		    <div class="col-sm-9">
		      <input type="password" class="form-control" id="inputPassword3" placeholder="Confirm password" name="password_confirm" required>
		    </div>
		  </div>
		  
		  <div class="form-group">
		    <div class="col-sm-offset-3 col-sm-9">
		      <button type="submit" class="btn btn-primary">Save</button>
		    </div>
		  </div>
		</form>

    </div>


    <div role="tabpanel" class="tab-pane" id="quiz">

		<form class="form-horizontal" action="<?php echo $this->url->get("user/create-quiz");?>" method="POST">

		  <div class="form-group">
    		<h5 for="inputTitle1" >Topic: </h5>
		    <div class="col-sm-12">
		      <input type="text" class="form-control" id="inputTitle1" name="title" placeholder="Quiz topic goes here ..." required>
		    </div>
		  </div>

		  <div class="form-group">
		    <h5>Describe: </h5>

		  	<?php foreach($levels as $item):?>
		    <div class="col-sm-4">
		      <div class="checkbox">
		        <label>
		          <input name="levels[]" type="checkbox" value="<?php echo $item->id;?>"> <?php echo $item->name;?>
		        </label>
		      </div>
		    </div>
			<?php endforeach;?>

		  </div>

		  <div class="form-group">
		    <div class="col-sm-offset-5 col-sm-5">
		      <button type="submit" class="btn btn-primary">Next</button>
		    </div>
		  </div>
		</form>

    </div>


  </div>

</div>

<script type="text/javascript">

$(document).ready(function() {


});

</script>