<?php echo $this->getContent(); ?>

	<?php $this->flashSession->output();?>

<h4>Forgot your password?</h4>
<form class="form-horizontal" action="<?php echo $this->url->get("signin/reset-password");?>" method="POST">

		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-4 control-label">Email: </label>
		    <div class="col-sm-4">
		      <input type="email" class="form-control" id="inputEmail3" name="email" placeholder="email@example.com" required autofocus>
		    </div>
		  </div>

		  <div class="form-group">
		    <label for="inputCaptchaImage" class="col-sm-4 control-label">Captcha: </label>
		    <div class="col-sm-4">
		    <img src="<?php echo $this->url->get("signin/captcha")?>" id="captcha"> 
		    <a href="javascript:void();" style="font-size:18px;vertical-align: middle;" class="reload-captcha"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></a>
		    </div>
		  </div>

		  <div class="form-group">
		    <label for="inputCaptcha" class="col-sm-4 control-label">Type Characters: </label>
		    <div class="col-sm-4">
		      <input type="text" class="form-control" id="inputCaptcha" name="captcha" placeholder="Type the Text" required>
		    </div>
		  </div>

		  <div class="form-group">
		    <div class="col-sm-offset-4 col-sm-5">
		      <button type="submit" class="btn btn-primary">Reset</button>
		    </div>
		  </div>

</form>

<script type="text/javascript">

$(document).ready(function() {

	$("a.reload-captcha").click(function(e){
		e.preventDefault();
		var d = new Date();
		var img = $("img#captcha").attr("src");
		$("img#captcha").attr("src", img + "?cache=" + d.getTime());
	});

});


</script>